name: Tests

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Build and install package
        run: |
          pip install .
      - name: Run tests
        if: success() || failure()
        run: pytest --cov=bokeh_sampledata --cov-report=xml --color=yes tests/unit
